apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-169888588
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-169888588
    app.kubernetes.io/part-of: test-app-169888588
  name: python-basic-169888588
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-basic-169888588
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-basic-169888588
    spec:
      containers:
      - image: quay.io/hacdev/vyi99i9z-tenant/test-app-169888588/python-basic-169888588@sha256:7f059ccfc905992a9153270a1f94766110b7134cc50cad03eaa6c830fb84d0c2
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
